name = "whattowatch"
compatibility_date = "2026-08-01"
pages_build_output_dir = "public"

# After creating the database (see README), paste its id below.
[[d1_databases]]
binding = "DB"
database_name = "whattowatch"
database_id = "25245e52-7cf7-4774-982e-41461a3612e3"
